
sonar.projectKey=Proyecto-Integrador-2026-2_ClicHogar
sonar.organization=proyecto-integrador-2026-2

sonar.sources=frontend/src,backend/src

sonar.exclusions=**/node_modules/**,**/*.spec.ts,dist/**,frontend/.astro/**